spring.application.name=gateway

server.port=1010

# AUTH SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9090
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# COURSE SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[1].id=course-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/courses/**
